# 勉強になったコーディング集
ためになった実装集のメモ

### 必要なライブラリ等

In [1]:
import numpy as np

### numpy.newaxis

numpy.newaxisは配列や行列に対して新しい次元を追加できるオブジェクト。

例えば、N次元配列 `x` を考えると `x.shape = (N,)` ですが、numpy.newaxisを用いることで、

行ベクトル `x[numpy.newaxis, :].shape = (1,N)` としたり、

列ベクトル `x[:, numpy.newaxis].shape = (N,1)` としたりすることが可能です。

In [8]:
W = np.array([[1, 2, 3], [4, 5, 6]])
x = np.array([7, 8, 9])

print(W)
print(x)
print()

print(x[np.newaxis, :])  # two dimension
print()

print(x[:, np.newaxis])  # two dimension with different shape
print()

print(x[np.newaxis])  # x[np.newaxis,:]と同じ

[[1 2 3]
 [4 5 6]]
[7 8 9]

[[7 8 9]]

[[7]
 [8]
 [9]]

[[7 8 9]]


### numpy.tile
numpy.tileは配列を複製してタイル状に並べた新しい配列を生成する関数  
1次元配列はもちろん,2次元配列にも対応している。

In [21]:
print(x)
print()

print(np.tile(x, 2))
print()

print(np.tile(x, (3, 2))) # 3×2の二次元配列の要素がaになっているイメージ
print()

print(np.tile(x, (2,3,4))) # 3次元にも並べられる。
print()

print(np.tile(W, 2)) # 2次元配列でもOK
print()

[7 8 9]

[7 8 9 7 8 9]

[[7 8 9 7 8 9]
 [7 8 9 7 8 9]
 [7 8 9 7 8 9]]

[[[7 8 9 7 8 9 7 8 9 7 8 9]
  [7 8 9 7 8 9 7 8 9 7 8 9]
  [7 8 9 7 8 9 7 8 9 7 8 9]]

 [[7 8 9 7 8 9 7 8 9 7 8 9]
  [7 8 9 7 8 9 7 8 9 7 8 9]
  [7 8 9 7 8 9 7 8 9 7 8 9]]]

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]

